### ISSUE TITLE
mrkdwn_in support in attachments?

### ISSUE THREAD

**Issue by rafaljanicki** [ashwanthkumar/slack-go-webhook#12]
Hello,

First of all, thanks for the library!
Would it be possible to add a support `mrkdwn_in` in the library? It'd help to post e.g. stack traces

Best,
Rafal

**Comment by ashwanthkumar** [comment]
@rafaljanicki Thank you for the feature request. Would you be able to send in a PR? I would be happy to review and merge them. I'm currently short of time to work on this repo :(

**Comment by ashwanthkumar** [comment]
Fixed via #13
