### ISSUE TITLE
Please add v0.3 tag

### ISSUE THREAD

**Issue by wagyu298** [ashwanthkumar/slack-go-webhook#17]
Hi @ashwanthkumar ,
I installed slack-go-webhook to my project by [dep](https://github.com/golang/dep) command.
The dep command installed slack-go-webhook-v0.2.
My projects uses Attachment.MarkdownIn, but v0.2 does not include it, and go build failed.

Please add v0.3 (or other new version number) tag to the GitHub repository if you don't have any problems.
Thank you.

**Comment by ashwanthkumar** [comment]
@wagyu298 There you go - https://github.com/ashwanthkumar/slack-go-webhook/releases/tag/v0.3
